module Quo
  module Utilities
    module Compose
      def compose: (composable query1, composable query2, ?joins: untyped?) -> Quo::MergedQuery
      def composable_with?: (queryOrRel query) -> bool
    end
  end
end
