module Quo
  module Utilities
    interface _Wrapable
      def new: (**untyped options) -> query
    end

    module Wrap : _Wrapable
      def wrap: (composable query_rel_or_data, **untyped options) -> query
    end
  end
end
