module Quo
  class EagerQuery < Quo::Query
    def collection: () -> loadedQueryOrEnumerable
    def query: () -> loadedQueryOrEnumerable

    def relation?: () -> false
    def eager?: () -> true

    private

    def preload_includes: (untyped records, ?untyped? preload) -> untyped
    def underlying_query: () -> enumerable
    def unwrap_relation: (loadedQueryOrEnumerable collection) -> enumerable
  end
end
