module Quo
  class MergedQuery < Quo::Query
    def self.build_from_options: (queryOptions) -> MergedQuery

    def initialize: (relOrEnumerable merged, composable left, composable right, **untyped options) -> void

    @merged_query: relOrEnumerable

    def query: () -> relOrEnumerable

    def inspect: () -> ::String

    private

    attr_reader left: composable
    attr_reader right: composable
    def operand_desc: (composable operand) -> String
  end
end
