module Quo
  class WrappedQuery < Quo::Query
    def self.build_from_options: (**untyped options) -> WrappedQuery

    @wrapped_query:  ActiveRecord::Relation

    def initialize: (ActiveRecord::Relation query, **untyped options) -> void

    def query: () -> ActiveRecord::Relation
  end
end
